name: pipeline-commerce

x-airflow-common-env: &airflow-common-env
  AIRFLOW__CORE__EXECUTOR: LocalExecutor
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://etl_user:etl_password@postgres:5432/etl_warehouse
  AIRFLOW__WEBSERVER__SECRET_KEY: "46e46596f08c21a0c54a21e6217a73be"
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  PYTHONPATH: /opt/airflow

services:
  postgres:
    image: postgres:16
    container_name: etl_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./etl/sql:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10

  airflow-init:
    build:
      context: ./etl
      dockerfile: Dockerfile
    container_name: airflow_init
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      <<: *airflow-common-env
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "True"
    command: >
          bash -c "airflow db migrate &&
          airflow users create --username admin --password admin --firstname Airflow --lastname Admin --role Admin --email admin@example.com"
    volumes:
          - ./etl/dags:/opt/airflow/dags:ro
          - ./etl:/opt/airflow/etl:ro
          - ./data:/opt/airflow/data
          - ./etl/sql:/opt/airflow/sql:ro
          - ./etl/sql/post_load:/opt/airflow/sql/post_load:ro
          - airflow_logs:/opt/airflow/logs
    restart: "no"

  airflow-webserver:
    build:
      context: ./etl
    container_name: airflow_webserver
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment:
      <<: *airflow-common-env
    command: webserver
    ports:
      - "8080:8080"
    volumes:
      - ./etl/dags:/opt/airflow/dags:ro
      - ./etl/sql:/opt/airflow/sql:ro
      - ./etl:/opt/airflow/etl:ro
      - ./data:/opt/airflow/data
      - ./etl/tests:/opt/airflow/tests:ro
      - airflow_logs:/opt/airflow/logs

  airflow-scheduler:
    build:
      context: ./etl
      dockerfile: Dockerfile
    container_name: airflow_scheduler
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment:
      <<: *airflow-common-env
    command: scheduler
    volumes:
      - ./etl/dags:/opt/airflow/dags:ro
      - ./etl:/opt/airflow/etl:ro
      - ./etl/sql:/opt/airflow/sql:ro
      - ./data:/opt/airflow/data
      - ./etl/tests:/opt/airflow/tests:ro
      - airflow_logs:/opt/airflow/logs

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DASHBOARD_USER: ${DASHBOARD_USER}
      DASHBOARD_PASSWORD: ${DASHBOARD_PASSWORD}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-http://localhost:30030,http://127.0.0.1:30030}

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "30030:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  airflow_logs:
