apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipeline-commerce-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/REPLACE_ORG/pipeline-commerce.git
    targetRevision: main
    path: k8s/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: pipeline-commerce
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
